### ISSUE TITLE
Convert self to static ?

### ISSUE THREAD

**Issue by kocoten1992** [mantas-done/subtitles#1]
```php
self::load($from_file_path)->save($to_file_path);
```
should be
```php
static::load($from_file_path)->save($to_file_path);
```

I can't extends your class when you're using self, cause it always point to your class

**Comment by kocoten1992** [comment]
If you agree, I'll make a PR :smiley:

**Comment by mantas-done** [comment]
Sure, make it!
By the way, what additions are you making in your class. Maybe they are useful for everybody and would be a good pull request?

**Comment by mantas-done** [comment]
Congratulations on being the first contributor to this project :)
