### ISSUE TITLE
.ass support

### ISSUE THREAD

**Issue by costapombo1997** [mantas-done/subtitles#10]
Will this library get .ass support ? 

(it seems that this one has : https://github.com/captioning/captioning)

**Comment by mantas-done** [comment]
If somebody will write the code, I will gladly merge it. 
You just need to create two methods (documentation has chapter how to add new formats).

If you really need .ass support, you can try bribing me with a donation of a beer :)

**Comment by mantas-done** [comment]
Ass support was added
