### ISSUE TITLE
Install sciprt on website ?

### ISSUE THREAD

**Issue by macano13** [mantas-done/subtitles#14]
Hi,

Here is the noob question but please hep me in start just . How can I install this script on my website or VPS?

Please help me , thank you.

**Comment by kocoten1992** [comment]
you use composer before ?

```composer require mantas-done/subtitles```

https://github.com/mantas-done/subtitles/blob/master/README.md

**Comment by macano13** [comment]
No my friend, I didnt use composer. Can you please guide me on steps what do I need to edit and upload to my directory or maybe refer me some Tut ?
Thank you


Poslato sa mog Samsung Galaxy smart telefona.
-------- Originalna poruka --------Od: Chuong <notifications@github.com> Datum: 23.11.18.  00.29  (GMT+01:00) U: mantas-done/subtitles <subtitles@noreply.github.com> Cc: macano13 <macano333@gmail.com>, Author <author@noreply.github.com> Naslov: Re: [mantas-done/subtitles] Install sciprt on website ? (#14) 
you use composer before ?
composer require mantas-done/subtitles
https://github.com/mantas-done/subtitles/blob/master/README.md

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mantas-done/subtitles","title":"mantas-done/subtitles","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mantas-done/subtitles"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kocoten1992 in #14: you use composer before ?\r\n\r\n```composer require mantas-done/subtitles```\r\n\r\nhttps://github.com/mantas-done/subtitles/blob/master/README.md"}],"action":{"name":"View Issue","url":"https://github.com/mantas-done/subtitles/issues/14#issuecomment-441133478"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mantas-done/subtitles/issues/14#issuecomment-441133478",
"url": "https://github.com/mantas-done/subtitles/issues/14#issuecomment-441133478",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [mantas-done/subtitles] Install sciprt on website ? (#14)",
"sections": [
{
"text": "",
"activityTitle": "**Chuong**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@kocoten1992",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"mantas-done/subtitles\",\n\"issueId\": 14,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"mantas-done/subtitles\",\n\"issueId\": 14\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/mantas-done/subtitles/issues/14#issuecomment-441133478"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 415182043\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mantas-done** [comment]
If it is not clear how to use composer you can just download all files and include them in your script with:
include('file_name.php');
