### ISSUE TITLE
 tv.naver.com subtitles 

### ISSUE THREAD

**Issue by garry911** [mantas-done/subtitles#17]
Hi,

All others videos with vtt extension are working okay.
But i have issue with one of the video from naver.com.
"  https://tv.naver.com/v/3678579 " . 
I have used getInternalFormat() ; It doesn't get the exact results. The time line is empty in some indexes
can you please check this issue.

Thanks

**Comment by kocoten1992** [comment]
the link is here: https://caption-rmcnmv.pstatic.net/tvcast/global_meta/read/TVCAST_2018_07_30_4/098c9050-939f-11e8-b4a9-3ca82a22d795-1532917190428_en_US_cp.vtt?__gda__=1548905899_d395325551ac449a0a3317d8f4edf7ed&

```
WEBVTT

1
00:00:19.671 --> 00:00:23.292
Hello! I'm "Faker" Lee Sang-hyeok,
the SKT T1 mid laner.

2
00:00:23.292 --> 00:00:28.898


3
00:00:28.898 --> 00:00:33.943
Today I'm gonna give you some advices
about how to play the Mid via Naver.

4
00:00:33.943 --> 00:00:33.982
If you follow along this video clip,
you'll play against me one day.

5
00:00:33.982 --> 00:00:39.431
```

Some WEBVTT just don't follow standard (one empty line instead of two between block), should we loose the standard and support them as well @mantas-done ?

**Comment by garry911** [comment]
I think we need to support them as well. What thing I need to edit to get the best results in your repository.

**Comment by kocoten1992** [comment]
I think it here, https://github.com/mantas-done/subtitles/blob/master/src/code/Converters/VttConverter.php#L9

**Comment by garry911** [comment]
Hi,
while formatting the time for " https://vimeo.com/229603434 " video link
I have found another bug after array => 400 the seconds are not accurate.
it again starts with zero. How to sort this out issue also.

399
89760.41 --> 89880.85 

400
89880.85 --> 0.38

**Comment by kocoten1992** [comment]
@garry911 yes, can confirm it

```
       "start" => 89640.16,
       "end" => 89760.41,
       "lines" => [
         "itâs interesting for the brethren to observe",
       ],
     ],
     [
       "start" => 89760.41,
       "end" => 89880.85,
       "lines" => [
         "when it says: the kingdom of heaven, as",
       ],
     ],
     [
       "start" => 89880.85,
       "end" => 0.38,
       "lines" => [
         "the explanation was given, is related",
       ],
     ],
     [
       "start" => 0.38,
       "end" => 0.19,
       "lines" => [
         "to the churchâs period of time, the government",
       ],
     ],
```

Consider open another issue for it, thank you

**Comment by garry911** [comment]
> Probably the best option would be to remove blocks with empty text, like block 2 and 5 (see @kocoten1992 comment). This way we won't generate subtitles with no text.
> Also, it would be great to write unit tests for this case.

What code line should i add to remove empty text, like block 2 and 5. because I am not getting perfect format. 

Thanks,

**Comment by mantas-done** [comment]
Updated code, should be fixed now

**Comment by garry911** [comment]
Hi, 

Somethings are not correct. The time code is not correctly working. Please check this result.

Array
(
[0] => Array
(
[start] => 19.671
[end] => 23.292
[lines] => Array
(
[0] => Hello! I'm "Faker" Lee Sang-hyeok,
[1] => the SKT T1 mid laner.
)

)

[1] => Array
(
[start] => 180
[end] => 0
[lines] => Array
(
[0] => 00:00:28.898 --> 00:00:33.943
[1] => Today I'm gonna give you some advices
[2] => about how to play the Mid via Naver.
)

)

[2] => Array
(
[start] => 33.943
[end] => 33.982
[lines] => Array
(
[0] => If you follow along this video clip,
[1] => you'll play against me one day.
)

)

[3] => Array
(
[start] => 360
[end] => 0
[lines] => Array
(
[0] => 00:00:39.431 --> 00:00:44.801
)

)

[4] => Array
(
[start] => 420
[end] => 0
[lines] => Array
(
[0] => 00:00:44.801 --> 00:00:50.271
[1] => The players exchanged champion playing
[2] => missions among ourselves beforehand.
)

)

[5] => Array
(
[start] => 540
[end] => 0
[lines] => Array
(
[0] => 00:00:50.308 --> 00:00:55.704
[1] => Player Rather of Griffin gave
[2] => me a mission for Zed and
)

)

**Comment by kocoten1992** [comment]
Let me check it, it conflict with my logic not supporting `cue id`, I wan't write test earlier for that..

**Comment by garry911** [comment]
Okay. 
I will wait for this fix. As I have checked after empty text. It gives zero in part:[1] in array.

**Comment by mantas-done** [comment]
The parsing of files was improved. Now it should parse that file. Report if you still have problems :)
