### ISSUE TITLE
WEBVTT wrong internal format mm:ss if mm > 24

### ISSUE THREAD

**Issue by kocoten1992** [mantas-done/subtitles#18]
Thanks @garry911 for pointing out

https://github.com/mantas-done/subtitles/issues/17#issuecomment-459574050

```
WEBVTT

24:50.990 --> 24:54.100
is like, the kingdom of heaven is like

24:54.160 --> 24:56.410
itâs interesting for the brethren to observe

24:56.410 --> 24:58.850
when it says: the kingdom of heaven, as

24:58.850 --> 25:01.380
the explanation was given, is related

25:01.380 --> 25:04.190
to the churchâs period of time, the government

25:04.190 --> 25:06.580
of Lord Jesus over His church

25:06.580 --> 25:09.590
throughout her existence through His

25:09.590 --> 25:13.420
Holy Spirit, amen? Now, letâs go to

25:13.420 --> 25:16.060
the next question, weâll allow to give

```

```php
use \Done\Subtitles\Subtitles;

$subtitles = Subtitles::load('sub.vtt');

$subtitles->getInternalFormat();
```

**Comment by kocoten1992** [comment]
This raise a few another issue, let say we have a format file:

```
WEBVTT

25:01.380 --> 25:04.190
to the churchâs period of time, the government

01:00:09.000 --> 01:00:11.000
<v Roger Bingham>We are in New York City

```

1. at first they might use `mm:ss` format but the then they use `hh:mm:ss` format, for easy maybe we just internal convert all into `hh:mm:ss` regardless of what they use

2. and when convert it back, maybe we should always support hh:mm:ss `00:25:01.380 --> 00:25:04.190`, this make thing easier for us, instead of checking max time and do complex conditional ? cc @mantas-done

**Comment by garry911** [comment]
Hi 
Should I update my repository? Or need some code to edit. 
:)

**Comment by kocoten1992** [comment]
Hi, this should fix sub-issue on #17 

could you make a PR to address #17 :wink:

**Comment by garry911** [comment]
PR ?? I didn't understand.

**Comment by mantas-done** [comment]
About supporting 2\. 00:25:01.380 --> 00:25:04.190 internally
it will not work, because some formats use frame number instead of time. So

**Comment by garry911** [comment]
Hi, 

Have you noticed this video url " https://tv.naver.com/v/3678579 " time code  formatting?
 I need to fix this as well. Because editing code line may also effect other videos also.

Thanks

**Comment by kocoten1992** [comment]
> Hi,
> 
> Have you noticed this video url " https://tv.naver.com/v/3678579 " time code formatting?
> I need to fix this as well. Because editing code line may also effect other videos also.
> 
> Thanks

You could either dug your hand into the mud, start debug and fix it, or wait me to fix, at your options
