### ISSUE TITLE
\n -> \r\n reason question

### ISSUE THREAD

**Issue by osavchenko** [mantas-done/subtitles#21]
Hello! Any reason to change `\n` to `\r\n` line endings?

**Comment by kminek** [comment]
@osavchenko i also noticed this. looks like a bug to me. converter should not mess with input file line-endings - if it gets LF it outputs LF, if it gets CRLF -> CRLF.

**Comment by mantas-done** [comment]
I think it was for Travis unit test support. 

But I don't know which one is better. If somebody needs a certain line endings, I can add an option which line ending to output.
->endings("\n")
or
->endings("\r\n")

But probably it doesn't matter which endings are used.
