### ISSUE TITLE
How do we add styles to .ass format subtitles.

### ISSUE THREAD

**Issue by Mahmood-Hussain** [mantas-done/subtitles#25]
I want to change the styling of subtitles programmatically how to do that?
![image](https://user-images.githubusercontent.com/31275645/80854447-0f4cf800-8c56-11ea-833d-a0d6c4796ee5.png)

like I want change font family, background color etc

**Comment by mantas-done** [comment]
Currently, there is no way to add styles through this library. Default ones should work for the most.

If you just want to change global styles, do a str_replace after the file is generated.
