### ISSUE TITLE
ANSI To UTF-8 ?

### ISSUE THREAD

**Issue by foremtehan** [mantas-done/subtitles#26]
I have some srt file that contains weird characters (ANSI? i think) I do fix it by notepad++ like this:

![output](https://user-images.githubusercontent.com/53290883/80879986-47dde780-8cd1-11ea-9a73-3b32c9f8dc24.gif)

Is this repo able to do that too?

file for test:

[ANSI.zip](https://github.com/mantas-done/subtitles/files/4568634/ANSI.zip)

**Comment by mantas-done** [comment]
No. File encoding has nothing to do with subtitles.
If you want to fix it automatically, you can use https://www.php.net/manual/en/function.mb-convert-encoding.php

**Comment by mantas-done** [comment]
Actually, it was added to the subtitling library. Now it tries to automatically fix the encoding.
