### ISSUE TITLE
Ass converto removes all lines in some srt files

### ISSUE THREAD

**Issue by foremtehan** [mantas-done/subtitles#27]
I tried to convert this file: 
[PersianSub.zip](https://github.com/mantas-done/subtitles/files/4580666/PersianSub.zip)

to ass format but it deleted all lines and output was only: 

```
'[Script Info]
; This is an Advanced Sub Station Alpha v4+ script.
Title: subtitles
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H0300FFFF,&H00000000,&H02000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text
'
```

```php
Subtitles::convert('PersianSub.srt', 'PersianSub.ass');
```

**Comment by mantas-done** [comment]
Probably regex needs to be fixed to select hieroglyphs also. 
If anyone is willing to fix it I would gladly accept a pull request. Or you will need to wait till I will have spare time.

**Comment by mantas-done** [comment]
Investigated this issue. File encoding is not UTF-8. After converting the file to UTF-8 with the Notepad++ file works.

**Comment by mantas-done** [comment]
Now the library automatically detects encoding. Your file is now parsing correctly.

**Comment by foremtehan** [comment]
Thank you for this amount of work!
