### ISSUE TITLE
Ability to override .ass metadata

### ISSUE THREAD

**Issue by foremtehan** [mantas-done/subtitles#32]
When converting subtitles to .ass format it always put the default metadata:

https://github.com/mantas-done/subtitles/blob/d449c29985d6c106171611e3b6ae6c52ff3a86f2/src/code/Converters/AssConverter.php#L20-L35

It would be nice if we could override all of metadata from `$file_content` variable because i always replace with my own but with extra regex

**Comment by mantas-done** [comment]
Probably for now it is the best option to replace with regex.
Every format has different styles and there would be a lot of changes needed.
