### ISSUE TITLE
remove styles in ass

### ISSUE THREAD

**Issue by KarimQaderi** [mantas-done/subtitles#34]
Hi
How can I delete the styles inside the ass subtitle?

like https://sorz.github.io/asstosrt-wasm/

![image](https://user-images.githubusercontent.com/32425175/113619044-b8be1a00-966d-11eb-9233-29f38ffd1cc7.png)

**Comment by sometimefly** [comment]
$subtitles = Subtitles::load('movie.vtt');
$subtitles = $subtitles->content('vtt');
$subtitles = preg_replace('/{(.*?)}/', '', $subtitles);
var_dump($subtitles);

**Comment by mantas-done** [comment]
Fixed this. Thank you for the report.
