### ISSUE TITLE
saved subtitle files not UTF-8

### ISSUE THREAD

**Issue by webwamp** [mantas-done/subtitles#37]
when saving subtitle in any formats (srt, sub, ...) the file should be UTF-8 for some languages like Persian, Arabic, ...
but when save subtitle file, this is not UTF-8 and when use subtitle in video player, the text be unreadable and should copy text into new text file as UTF-8 encoding and save and change text file format to subtitle like srt

i try to use mb_convert_encoding() and utf8_encode() in save function to fix content, but the problem is the saving class not subtitle content, so it is better to fixing this and update git

**Comment by mantas-done** [comment]
@webwamp  Hi, can you make a minimal example of code that saves a bad file? 
Please attach the code and the file and I will take a look at it.

**Comment by mantas-done** [comment]
Closing this issue. Create a new one if you will still need the change.
