### ISSUE TITLE
not issue, this is EXTRA Function for users "addToEnd" function (Source Code)

### ISSUE THREAD

**Issue by webwamp** [mantas-done/subtitles#38]
i am adding one useful function to source for myself and it is work very nice, you can use that too if you want ...
this function add line/lines to end of the subtitles without need to set start/end show time, i named as "addToEnd()"

`public function add(){...} // main function of the source`

`public function addToEnd($time,$text){`
`	// first get the maxTime`
`	// [Optional] adding 1 seconds to show this line one seconds after the last line`
`	$MaxTime = $this->maxTime() + 1;`
`	`
`	// Calculate End time to Show`
`	$EndTime = $MaxTime + $time;`
`	`
`	// call add function`
`	$this->add($MaxTime,$EndTime,$text);`
`}`

and if you want minified version, use this:

`public function addToEnd($s,$t){$m=$this->maxTime()+1;$this->add($m,$m+$s,$t);}`

**Comment by mantas-done** [comment]
With a recent change maxTime is public.

you can do now:
```
$subtitles = Subtitles::load('subtitles.srt');
$subtitles->add($subtitles->maxTime(), $subtitles->maxTime() + 1, 'Text');
```
