### ISSUE TITLE
Why we do not have ability to set identifier in vtt file? 

### ISSUE THREAD

**Issue by bearn666** [mantas-done/subtitles#39]
Why we do not have ability to set identifier in vtt file? 
Example:
```
WEBVTT

1 (i mean this identifier)
00:02:34.950 --> 00:02:35.961
A ver si sale la pava esta


2
00:02:35.985 --> 00:02:38.578
y nos ponemos en marcha de una puta vez.

```

**Comment by mantas-done** [comment]
Identifiers always start from one and increment.  What would be the use case to manually set them?

**Comment by mantas-done** [comment]
Actually, identifiers in vtt file aren't only integres. If you would like to add support for that. I can guide you and would merge your PR.
