### ISSUE TITLE
Losing milliseconds

### ISSUE THREAD

**Issue by rudnypc** [mantas-done/subtitles#45]
Hi,

When I decode the vtt file, the system show that time
start 3
end 5,644
 
When I use the command "$subtitles->content('vtt');", I receive that string without milliseconds
00:00:03.000 --> 00:00:05.000
 
The original:
00:00:03.000 --> 00:00:05.644

**Comment by mantas-done** [comment]
can't reproduce this, please supply more data
the perfect example would be code that i can run and see the problem
