### ISSUE TITLE
iTunes Timed Text reader and writer

### ISSUE THREAD

**Issue by chenlung** [mantas-done/subtitles#46]
Specification available at [Apple](https://www.apple.com/euro/itunes/lp-and-extras/docs/iTunes_Package_Film_Specification5.0.pdf).

Sample files: [iTunes Timed Text.zip](https://github.com/mantas-done/subtitles/files/9742896/iTunes.Timed.Text.zip)

**Comment by mantas-done** [comment]
Good news, ttml format support was improved and now this converter can parse and save files in that format.
