### ISSUE TITLE
Failed to convert srt string to vtt

### ISSUE THREAD

**Issue by adis0308** [mantas-done/subtitles#78]
I'm having trouble converting SRT strings to VTT. There are additional unrecognized unicode character in the SRT strings.
Example: https://subs.warezcdn.net/84-PT.srt

**Comment by mantas-done** [comment]
[test.vtt.txt](https://github.com/mantas-done/subtitles/files/12211779/test.vtt.txt)

With the latest library version, the file is converted. Please check the attached file.
If there still will be unrecognized characters, please attach the vtt file and write which library version are you using.
