### ISSUE TITLE
Unicode problem. in SmiConverter.php

### ISSUE THREAD

**Issue by hyoungki-kim** [mantas-done/subtitles#87]
Hello.

The unicode character broken, when load smi.
This is the code.
```
@$doc->loadHTML($file_content); // silence warnings about invalid html
```
Insert this code please. Before loadHTML. like this...
```
$file_content = mb_convert_encoding($file_content, 'HTML-ENTITIES', "UTF-8");
@$doc->loadHTML($file_content); // silence warnings about invalid html
```

**Comment by mantas-done** [comment]
Hi, can you also add the file that is having the problem. I will use it for the unit test.

**Comment by hyoungki-kim** [comment]
This is the file. (Language is korean)
[sbs-das_2023.zip](https://github.com/mantas-done/subtitles/files/13807046/sbs-das_2023.zip)

**Comment by hyoungki-kim** [comment]
You can also refer to a comment on php.net.
That comment is as follows.

=====================================

Text-encoding HTML-ENTITIES will be deprecated as of PHP 8.2.

To convert all non-ASCII characters into entities (to produce pure 7-bit HTML output), I was using:

```php
echo mb_convert_encoding( htmlspecialchars( $text, ENT_QUOTES, 'UTF-8' ), 'HTML-ENTITIES', 'UTF-8' );
```

I can get the identical result with:

```php
echo mb_encode_numericentity( htmlentities( $text, ENT_QUOTES, 'UTF-8' ), [0x80, 0x10FFFF, 0, ~0], 'UTF-8' );
```

The output contains well-known named entities for some often used characters and numeric entities for the rest.

**Comment by mantas-done** [comment]
Thank you. Updated the code and released a new package version.
