### ISSUE TITLE
Srt files sometimes get time with 4 digits at milliseconds

### ISSUE THREAD

**Issue by leandrosimoes** [mantas-done/subtitles#88]
Hi,

I have noticed that after the conversion some `.srt` files could not load properly in some players, and after expending some time trying to understand I was able to check that the problem is because some timestamps in the generated `.srt` file had some lines with the milliseconds with a four-digit format as you can see in the image below:

![Screenshot 2024-01-30 at 09 37 29](https://github.com/mantas-done/subtitles/assets/5066378/02feb129-9826-4af8-8161-2574c4d68978)

Here is the `.scc` file that I used to convert to `.srt` in case you want to test it:

[test.scc.zip](https://github.com/mantas-done/subtitles/files/14095030/test.scc.zip)

FYI I know about the weird starting timestamp at hour 03, but this is just a sample file.

Do you think this is a bug?

Thanks!

**Comment by mantas-done** [comment]
Hi, thank you for the bug report.
I have fixed it, you can do a "composer update" to get the fixed code :)
https://github.com/mantas-done/subtitles/commit/77e0f26fbbf7e8c0f0de1b17368b5a27a1cbae87
