### ISSUE TITLE
MicroDVD converter expects dot at the end of line

### ISSUE THREAD

**Issue by choks87** [mantas-done/subtitles#90]
Issue at: https://github.com/mantas-done/subtitles/blob/20b84a593af883318aac8a325f6d5ed2bf95874e/src/Code/Converters/SubMicroDvdConverter.php#L11
```
\Done\Subtitles\Code\Converters\SubMicroDvdConverter
```

Cannot convert micro DVD of content:
```
{0}{100}Subtitle line 1
{150}{300}Subtitle line 2
{350}{550}Subtitle line 3
```

Because regex is `/\{\d+\}\{\d+\}(.*)\./` .
It matches this one:
```
{0}{100}Subtitle line 1.
{150}{300}Subtitle line 2.
{350}{550}Subtitle line 3.
```

There is a [dot] at the end, by removing `/\{\d+\}\{\d+\}(.*)`
it accepts.

Not sure if it's by design or which standard. I found this articles:
https://docs.fileformat.com/video/sub/
https://en.wikipedia.org/w/index.php?title=MicroDVD&oldid=1179638991

and both are saying that format is:
```
{start-frame}{stop-frame}Text
```

**Comment by mantas-done** [comment]
@choks87 Fixed.
